version: "3"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: m_money
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://root:root@db:3306/m_money
      JWT_SECRET: 7c4e1b8a0f9d3c6e2a5b9f1d4c7e0a3b6f8e2d9c1a4b7f0
      REFRESH_SECRET: 9d2a6f3b8c1e0a4f7d9b3e6c2f1a8d0b4e7c9f3a1b6e2d8
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
volumes:
  db-data:
